require 'bundler/audit/cli'

task :clean do |t|
  puts "Cleaning"
end 

namespace :bundle_audit do
  desc 'Update bundle-audit database'
  task :update do
    Bundler::Audit::CLI.new.update
  end

  desc 'Check gems for vulns using bundle-audit'
  task :check do
    Bundler::Audit::CLI.new.check
  end

  desc 'Update vulns database and check gems using bundle-audit'
  task :run do
    Rake::Task['bundle_audit:update'].invoke
    Rake::Task['bundle_audit:check'].invoke
  end
end

begin
  require 'rspec/core/rake_task'
  namespace :spec do
    RSpec::Core::RakeTask.new(:unit) do |t|
      t.pattern = 'src/spec/**{,/*/**}/*_spec.rb'
      t.rspec_opts = ['--format h', '--out reports/tests/index.html']
    end
  end
rescue LoadError
end

task :dependency_check do
  Rake::Task['bundle_audit:run'].invoke
end
